const images = {
  pilot: require("./pilot.png"),
  karina: require("./karina.webp"),
  karinaSmile: require("./karinaSmile.webp"),
  missGrandVn: require("./missGrandVn.png"),
  missGrandTL: require("./missGrandTL.png"),
  y2k: require("./y2k.png"),
  bbnm: require("./bbnm.png"),
  classicMan: require("./ClassicMan.png"),
  classicWoman: require("./ClassicWoman.png"),
  whiteWedding: require("./whiteWedding.png"),
  pinkWedding: require("./PinkWedding.png"),
  userIcon: require("./userIcon.svg"),
  homeBg: require("./homeBg.png"),
  authBg: require("./authBg.png"),
  regularBg: require("./regularBg.png"),
  changePasswordBg: require("./changePasswordBg.png"),
  maleIcon: require("./male_icon.png"),
  femaleIcon: require("./female_icon.png"),
  startScreen: require("./startSrceen.png"),
  startImage:require("./startGirl.png"),
  startImageOne: require("./sexyGirl1.png"),
  startImageTwo: require("./sexyGirl2.png"),
  startImageThree: require("./sexyGirl3.png"),
  startImageFour: require("./sexyGirl4.png"),
  startImageFive: require("./sexyGirl5.png"),
  startImageSix: require("./sexyGirl6.png"),
  // startImageSeven: require("./sexyGirl7.png"),
  // startImageEight: require("./sexyGirl8.png"),
  // startImageNine: require("./sexyGirl9.png"),
};

export default images;
